"""v3

Revision ID: 1e2c36e992fe
Revises: f71c70606c45
Create Date: 2025-01-02 05:02:29.734713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e2c36e992fe'
down_revision: Union[str, None] = 'f71c70606c45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
            ALTER TABLE choices
            ALTER COLUMN true_answer
            TYPE BOOLEAN
            USING (
                CASE
                    WHEN true_answer ILIKE 'true' THEN true
                    WHEN true_answer ILIKE 'false' THEN false
                    WHEN true_answer = '1' THEN true
                    WHEN true_answer = '0' THEN false
                END
            )""")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('choices', 'true_answer',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
