"""2 ver

Revision ID: 75eed3fe1a0f
Revises: 782e31d31682
Create Date: 2025-01-02 04:14:22.425662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75eed3fe1a0f'
down_revision: Union[str, None] = '782e31d31682'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('choices', sa.Column('choice', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('choices', 'choice')
    # ### end Alembic commands ###
