"""add question num

Revision ID: 97edcb57f00b
Revises: 5022d1af7b8d
Create Date: 2025-01-02 21:05:25.108538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97edcb57f00b'
down_revision: Union[str, None] = '5022d1af7b8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userquizsessions', sa.Column('question_num', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userquizsessions', 'question_num')
    # ### end Alembic commands ###
