"""update quiz session table

Revision ID: d5647b1b2d33
Revises: d5cd862c4e4d
Create Date: 2025-01-02 18:02:11.057675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5647b1b2d33'
down_revision: Union[str, None] = 'd5cd862c4e4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userquizsessions', sa.Column('session_id', sa.String(), nullable=False))
    op.drop_column('userquizsessions', 'selected_choice')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userquizsessions', sa.Column('selected_choice', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('userquizsessions', 'session_id')
    # ### end Alembic commands ###
