"""to lower for login and email v5

Revision ID: fdda3c97181a
Revises: a259ad47087e
Create Date: 2025-01-04 19:55:06.813230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdda3c97181a'
down_revision: Union[str, None] = 'a259ad47087e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('login', sa.String(), nullable=False))
    op.add_column('users', sa.Column('email', sa.String(), nullable=False))
    op.drop_constraint('users__email_key', 'users', type_='unique')
    op.drop_constraint('users__login_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['login'])
    op.create_unique_constraint(None, 'users', ['email'])
    op.drop_column('users', '_login')
    op.drop_column('users', '_email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('_email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('_login', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint('users__login_key', 'users', ['_login'])
    op.create_unique_constraint('users__email_key', 'users', ['_email'])
    op.drop_column('users', 'email')
    op.drop_column('users', 'login')
    # ### end Alembic commands ###
